spring.application.name=acadence-user-management
# Set the active Spring profile (local, dev, prod)
spring.profiles.active=local

# --- Server Configuration ---
# Sets the port the application will run on (default is 8092)
server.port=8892

